server:
  port: 0             # Port par défaut du serveur
spring:
  application:
    name: auth-service

security:
  cors:
    allowed-origins: http://localhost:3000
  jwt:
    secret: 9a4f2c_8d3b7a1e6f#45c8a0b3f268b1d4e6-f3c8a9d2b5f8e3a9c8-b5f6v8a3d9A@
    expiration-time: 86400000
  is-ssl: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
    fetch-registry: true  # Le client doit récupérer les services
    register-with-eureka: true  # Le client s'enregistre dans le registre
  instance:
    prefer-ip-address: true  # Utilise l'adresse IP pour l'enregistrement (utile pour les environnements containerisés)


springdoc:
  api-docs:
    group: authentication